import 'dotenv/config';
import { supabase } from '../supabase';

const VOCAB_ITEMS = [
  // ── HISTORY ─────────────────────────────────────────────────────────────────
  { question: 'гражданство',               question_el: 'ιθαγένεια',                    correct_answer: 'гражданство',               explanation: 'Право принадлежать к государству',                topic: 'vocab' },
  { question: 'натурализация',             question_el: 'πολιτογράφηση',                correct_answer: 'натурализация',             explanation: 'Получение гражданства иностранцем',               topic: 'vocab' },
  { question: 'революция',                 question_el: 'Επανάσταση',                   correct_answer: 'революция',                 explanation: '1821 — восстание против османского владычества',   topic: 'vocab' },
  { question: 'независимость',             question_el: 'ανεξαρτησία',                  correct_answer: 'независимость',             explanation: 'Греция обрела независимость в 1821–1832 гг.',      topic: 'vocab' },
  { question: 'конституция',               question_el: 'Σύνταγμα',                     correct_answer: 'конституция',               explanation: 'Основной закон государства',                       topic: 'vocab' },
  { question: 'оккупация',                 question_el: 'κατοχή',                       correct_answer: 'оккупация',                 explanation: 'Немецко-итальянская оккупация Греции 1941–1944',   topic: 'vocab' },
  { question: 'сопротивление',             question_el: 'αντίσταση',                    correct_answer: 'сопротивление',             explanation: 'Борьба с оккупантами во Второй мировой',           topic: 'vocab' },
  { question: 'гражданская война',         question_el: 'Εμφύλιος (πόλεμος)',           correct_answer: 'гражданская война',         explanation: 'Греческая гражданская война 1946–1949 гг.',        topic: 'vocab' },
  { question: 'диктатура',                 question_el: 'δικτατορία',                   correct_answer: 'диктатура',                 explanation: 'Военная хунта в Греции 1967–1974 гг.',              topic: 'vocab' },
  { question: 'демократизация после хунты',question_el: 'μεταπολίτευση',               correct_answer: 'демократизация после хунты',explanation: 'Переход к демократии после хунты в 1974 г.',       topic: 'vocab' },
  { question: 'Византия',                  question_el: 'Βυζάντιο',                     correct_answer: 'Византия',                  explanation: 'Средневековая греческая империя (330–1453)',        topic: 'vocab' },
  { question: 'Османская империя',         question_el: 'Οθωμανική Αυτοκρατορία',       correct_answer: 'Османская империя',         explanation: 'Держава, под властью которой Греция была 400 лет', topic: 'vocab' },
  { question: 'Мировая война',             question_el: 'Παγκόσμιος Πόλεμος',           correct_answer: 'Мировая война',             explanation: 'Β΄ Παγκόσμιος Πόλεμος — Вторая мировая война',    topic: 'vocab' },
  { question: 'освобождение',              question_el: 'απελευθέρωση',                 correct_answer: 'освобождение',              explanation: 'Освобождение Афин 12 октября 1944 г.',             topic: 'vocab' },
  { question: 'геноцид',                   question_el: 'γενοκτονία',                   correct_answer: 'геноцид',                   explanation: 'Геноцид понтийских греков в 1914–1923 гг.',        topic: 'vocab' },
  { question: 'монархия',                  question_el: 'μοναρχία',                     correct_answer: 'монархия',                  explanation: 'Форма правления с королём во главе',               topic: 'vocab' },
  { question: 'национализм',               question_el: 'εθνικισμός',                   correct_answer: 'национализм',               explanation: 'Идеология приоритета национальных интересов',      topic: 'vocab' },
  { question: 'Холокост',                  question_el: 'Ολοκαύτωμα',                   correct_answer: 'Холокост',                  explanation: 'Уничтожение евреев нацистами, в т.ч. в Греции',    topic: 'vocab' },
  { question: 'колония',                   question_el: 'αποικία',                      correct_answer: 'колония',                   explanation: 'Зависимая территория другого государства',         topic: 'vocab' },
  { question: 'реформа',                   question_el: 'μεταρρύθμιση',                 correct_answer: 'реформа',                   explanation: 'Преобразование в какой-либо сфере жизни',          topic: 'vocab' },
  { question: 'восстание',                 question_el: 'εξέγερση',                     correct_answer: 'восстание',                 explanation: 'Вооружённое выступление против власти',            topic: 'vocab' },
  { question: 'перемирие',                 question_el: 'ανακωχή',                      correct_answer: 'перемирие',                 explanation: 'Прекращение военных действий по соглашению',       topic: 'vocab' },
  { question: 'договор',                   question_el: 'συνθήκη',                      correct_answer: 'договор',                   explanation: 'Лозаннский договор 1923 г. — обмен населением',    topic: 'vocab' },
  { question: 'завоевание',                question_el: 'κατάκτηση',                    correct_answer: 'завоевание',                explanation: 'Захват территории военной силой',                  topic: 'vocab' },
  { question: 'Балканы',                   question_el: 'Βαλκάνια',                     correct_answer: 'Балканы',                   explanation: 'Полуостров на юго-востоке Европы',                 topic: 'vocab' },
  { question: 'Малоазийская катастрофа',   question_el: 'Μικρασιατική Καταστροφή',      correct_answer: 'Малоазийская катастрофа',   explanation: 'Поражение Греции в Турции и исход 1922 г.',        topic: 'vocab' },
  { question: 'обмен населением',          question_el: 'ανταλλαγή πληθυσμών',          correct_answer: 'обмен населением',          explanation: 'Грекo-турецкий обмен 1923 г. по Лозаннскому дог.', topic: 'vocab' },
  { question: 'фашизм',                    question_el: 'Φασισμός',                     correct_answer: 'фашизм',                    explanation: 'Тоталитарная идеология, против которой воевала Греция', topic: 'vocab' },
  { question: 'Холодная война',            question_el: 'Ψυχρός Πόλεμος',              correct_answer: 'Холодная война',            explanation: 'Противостояние США и СССР после 1945 г.',          topic: 'vocab' },
  { question: 'национальная память',       question_el: 'εθνική μνήμη',                 correct_answer: 'национальная память',       explanation: 'Коллективная память народа о важных событиях',    topic: 'vocab' },
  { question: 'Третья Греческая Республика',question_el: 'Γ΄ Ελληνική Δημοκρατία',    correct_answer: 'Третья Греческая Республика',explanation: 'Демократическая Греция с 1974 г. по наст. время', topic: 'vocab' },
  { question: 'древность, античность',     question_el: 'αρχαιότητα',                   correct_answer: 'древность, античность',     explanation: 'Период до конца Западной Римской империи',         topic: 'vocab' },
  { question: 'средние века',              question_el: 'Μεσαίωνας',                    correct_answer: 'средние века',              explanation: 'Период между античностью и Новым временем',        topic: 'vocab' },
  { question: 'Великая идея',              question_el: 'Μεγάλη Ιδέα',                 correct_answer: 'Великая идея',              explanation: 'Греческая нац. идея воссоединения всех греков',    topic: 'vocab' },
  { question: 'Балканские войны',          question_el: 'Βαλκανικοί Πόλεμοι',          correct_answer: 'Балканские войны',          explanation: 'Войны 1912–1913 гг. за территории Балкан',         topic: 'vocab' },
  // ── LAWS ────────────────────────────────────────────────────────────────────
  { question: 'парламент',                 question_el: 'Βουλή',                        correct_answer: 'парламент',                 explanation: 'Законодательный орган Греции — 300 депутатов',     topic: 'vocab' },
  { question: 'Президент Республики',      question_el: 'Πρόεδρος της Δημοκρατίας',     correct_answer: 'Президент Республики',      explanation: 'Глава государства, избирается парламентом',        topic: 'vocab' },
  { question: 'Премьер-министр',           question_el: 'Πρωθυπουργός',                 correct_answer: 'Премьер-министр',           explanation: 'Глава правительства Греции',                       topic: 'vocab' },
  { question: 'министр',                   question_el: 'Υπουργός',                     correct_answer: 'министр',                   explanation: 'Руководитель министерства в правительстве',        topic: 'vocab' },
  { question: 'правительство',             question_el: 'Κυβέρνηση',                    correct_answer: 'правительство',             explanation: 'Исполнительная власть страны',                     topic: 'vocab' },
  { question: 'министерство',              question_el: 'Υπουργείο',                    correct_answer: 'министерство',              explanation: 'Ведомство, управляющее отдельной сферой',          topic: 'vocab' },
  { question: 'выборы',                    question_el: 'εκλογές',                      correct_answer: 'выборы',                    explanation: 'Парламентские выборы каждые 4 года',               topic: 'vocab' },
  { question: 'голосование',               question_el: 'ψηφοφορία',                    correct_answer: 'голосование',               explanation: 'В Греции голосование обязательно с 17 лет',        topic: 'vocab' },
  { question: 'депутат',                   question_el: 'Βουλευτής',                    correct_answer: 'депутат',                   explanation: 'Член парламента — Βουλής',                          topic: 'vocab' },
  { question: 'закон',                     question_el: 'νόμος',                        correct_answer: 'закон',                     explanation: 'Принимается парламентом и подписывается президентом', topic: 'vocab' },
  { question: 'суд',                       question_el: 'Δικαστήριο',                   correct_answer: 'суд',                       explanation: 'Орган правосудия',                                 topic: 'vocab' },
  { question: 'судья',                     question_el: 'Δικαστής',                     correct_answer: 'судья',                     explanation: 'Лицо, осуществляющее правосудие',                  topic: 'vocab' },
  { question: 'прокурор',                  question_el: 'Εισαγγελέας',                  correct_answer: 'прокурор',                  explanation: 'Представитель государства в уголовном процессе',   topic: 'vocab' },
  { question: 'муниципалитет',             question_el: 'Δήμος',                        correct_answer: 'муниципалитет',             explanation: 'Основная единица местного самоуправления',         topic: 'vocab' },
  { question: 'мэр',                       question_el: 'Δήμαρχος',                     correct_answer: 'мэр',                       explanation: 'Руководитель муниципалитета',                       topic: 'vocab' },
  { question: 'регион',                    question_el: 'Περιφέρεια',                   correct_answer: 'регион',                    explanation: 'Греция поделена на 13 регионов',                   topic: 'vocab' },
  { question: 'губернатор',                question_el: 'Περιφερειάρχης',               correct_answer: 'губернатор',                explanation: 'Выборный руководитель региона',                    topic: 'vocab' },
  { question: 'партия',                    question_el: 'κόμμα',                        correct_answer: 'партия',                    explanation: 'Политическая организация для участия в выборах',   topic: 'vocab' },
  { question: 'оппозиция',                 question_el: 'αντιπολίτευση',                correct_answer: 'оппозиция',                 explanation: 'Партии, не входящие в правительство',              topic: 'vocab' },
  { question: 'право',                     question_el: 'δικαίωμα',                     correct_answer: 'право',                     explanation: 'Права человека закреплены в Конституции',          topic: 'vocab' },
  { question: 'обязанность',               question_el: 'υποχρέωση',                    correct_answer: 'обязанность',               explanation: 'Воинская обязанность — обязанность граждан',       topic: 'vocab' },
  { question: 'свобода',                   question_el: 'ελευθερία',                    correct_answer: 'свобода',                   explanation: 'Свобода слова, передвижения, вероисповедания',     topic: 'vocab' },
  { question: 'равенство',                 question_el: 'ισότητα',                      correct_answer: 'равенство',                 explanation: 'Все граждане равны перед законом',                 topic: 'vocab' },
  { question: 'заявление',                 question_el: 'αίτηση',                       correct_answer: 'заявление',                 explanation: 'Документ для подачи запроса в органы власти',      topic: 'vocab' },
  { question: 'бюллетень',                 question_el: 'ψηφοδέλτιο',                   correct_answer: 'бюллетень',                 explanation: 'Список кандидатов или партий для голосования',     topic: 'vocab' },
  { question: 'большинство',               question_el: 'πλειοψηφία',                   correct_answer: 'большинство',               explanation: 'Более половины голосов',                           topic: 'vocab' },
  { question: 'меньшинство',               question_el: 'μειοψηφία',                    correct_answer: 'меньшинство',               explanation: 'Менее половины голосов или представителей',        topic: 'vocab' },
  { question: 'кандидат',                  question_el: 'υποψήφιος',                    correct_answer: 'кандидат',                  explanation: 'Лицо, выдвигающееся на выборную должность',        topic: 'vocab' },
  { question: 'избиратель',                question_el: 'ψηφοφόρος',                    correct_answer: 'избиратель',                explanation: 'Гражданин, имеющий право голоса',                  topic: 'vocab' },
  { question: 'права человека',            question_el: 'ανθρώπινα δικαιώματα',          correct_answer: 'права человека',            explanation: 'Основные права и свободы каждого человека',        topic: 'vocab' },
  { question: 'правовое государство',      question_el: 'κράτος δικαίου',               correct_answer: 'правовое государство',      explanation: 'Государство, где власть ограничена законом',       topic: 'vocab' },
  { question: 'компетенция, полномочие',   question_el: 'αρμοδιότητα',                  correct_answer: 'компетенция, полномочие',   explanation: 'Круг обязанностей и прав органа власти',           topic: 'vocab' },
  { question: 'пропорциональная система',  question_el: 'αναλογική αντιπροσώπευση',      correct_answer: 'пропорциональная система',  explanation: 'Система выборов, где места пропорциональны голосам', topic: 'vocab' },
  { question: 'глава государства',         question_el: 'αρχηγός κράτους',              correct_answer: 'глава государства',         explanation: 'В Греции — Президент Республики',                  topic: 'vocab' },
  // ── GEOGRAPHY ───────────────────────────────────────────────────────────────
  { question: 'Аттика',                    question_el: 'Αττική',                       correct_answer: 'Аттика',                    explanation: 'Регион вокруг Афин, самый населённый',             topic: 'vocab' },
  { question: 'Салоники',                  question_el: 'Θεσσαλονίκη',                  correct_answer: 'Салоники',                  explanation: 'Второй по величине город Греции',                  topic: 'vocab' },
  { question: 'Крит',                      question_el: 'Κρήτη',                        correct_answer: 'Крит',                      explanation: 'Самый большой остров Греции',                       topic: 'vocab' },
  { question: 'Додеканесские острова',     question_el: 'Δωδεκάνησα',                   correct_answer: 'Додеканесские острова',     explanation: 'Острова в юго-восточной части Эгейского моря',     topic: 'vocab' },
  { question: 'Эгейское море',             question_el: 'Αιγαίο πέλαγος',              correct_answer: 'Эгейское море',             explanation: 'Море между Грецией и Турцией',                     topic: 'vocab' },
  { question: 'Ионическое море',           question_el: 'Ιόνιο πέλαγος',               correct_answer: 'Ионическое море',           explanation: 'Море к западу от Греции',                          topic: 'vocab' },
  { question: 'Средиземное море',          question_el: 'Μεσόγειος θάλασσα',           correct_answer: 'Средиземное море',          explanation: 'Море, омывающее Грецию с юга',                     topic: 'vocab' },
  { question: 'Пелопоннес',               question_el: 'Πελοπόννησος',                 correct_answer: 'Пелопоннес',               explanation: 'Крупный полуостров на юге Греции',                 topic: 'vocab' },
  { question: 'Македония',                 question_el: 'Μακεδονία',                    correct_answer: 'Македония',                 explanation: 'Регион на севере Греции, родина Александра Великого', topic: 'vocab' },
  { question: 'Фракия',                    question_el: 'Θράκη',                        correct_answer: 'Фракия',                    explanation: 'Регион на северо-востоке Греции',                  topic: 'vocab' },
  { question: 'Ионические острова',        question_el: 'Επτάνησα',                     correct_answer: 'Ионические острова',        explanation: 'Семь островов у западного побережья Греции',      topic: 'vocab' },
  { question: 'Эпир',                      question_el: 'Ήπειρος',                      correct_answer: 'Эпир',                      explanation: 'Горный регион на северо-западе Греции',            topic: 'vocab' },
  { question: 'Фессалия',                  question_el: 'Θεσσαλία',                     correct_answer: 'Фессалия',                  explanation: 'Равнинный регион в центре Греции',                 topic: 'vocab' },
  { question: 'Родос',                     question_el: 'Ρόδος',                        correct_answer: 'Родос',                     explanation: 'Крупнейший остров Додеканеса',                      topic: 'vocab' },
  { question: 'Корфу',                     question_el: 'Κέρκυρα',                      correct_answer: 'Корфу',                     explanation: 'Главный остров Ионических островов',               topic: 'vocab' },
  { question: 'Спарта',                    question_el: 'Σπάρτη',                       correct_answer: 'Спарта',                    explanation: 'Древний и современный город на Пелопоннесе',        topic: 'vocab' },
  { question: 'Коринф',                    question_el: 'Κόρινθος',                     correct_answer: 'Коринф',                    explanation: 'Город и Коринфский канал',                          topic: 'vocab' },
  { question: 'Дельфы',                    question_el: 'Δελφοί',                       correct_answer: 'Дельфы',                    explanation: 'Центр древнегреческого мира, оракул Аполлона',     topic: 'vocab' },
  { question: 'Олимп',                     question_el: 'Όλυμπος',                      correct_answer: 'Олимп',                     explanation: 'Высшая точка Греции (2917 м), обитель богов',       topic: 'vocab' },
  { question: 'столица',                   question_el: 'πρωτεύουσα',                   correct_answer: 'столица',                   explanation: 'Αθήνα — столица Греции',                           topic: 'vocab' },
  { question: 'остров',                    question_el: 'νησί',                         correct_answer: 'остров',                    explanation: 'В Греции более 6000 островов',                      topic: 'vocab' },
  { question: 'полуостров',                question_el: 'χερσόνησος',                   correct_answer: 'полуостров',                explanation: 'Пелопоннес — крупнейший полуостров Греции',        topic: 'vocab' },
  { question: 'граница',                   question_el: 'σύνορο',                       correct_answer: 'граница',                   explanation: 'Греция граничит с Алб., Болг., С.Маc., Турцией',   topic: 'vocab' },
  { question: 'соседние страны',           question_el: 'γειτονικές χώρες',             correct_answer: 'соседние страны',           explanation: 'Соседи Греции: Албания, Болгария, С.Мак., Турция', topic: 'vocab' },
  { question: 'Эвбея',                     question_el: 'Εύβοια',                       correct_answer: 'Эвбея',                     explanation: 'Второй по площади остров Греции',                  topic: 'vocab' },
  { question: 'Патры',                     question_el: 'Πάτρα',                        correct_answer: 'Патры',                     explanation: 'Третий по величине город, ворота Европы',          topic: 'vocab' },
  { question: 'материковый',               question_el: 'ηπειρωτικός',                  correct_answer: 'материковый',               explanation: 'Материковая Греция в отличие от островной',        topic: 'vocab' },
  { question: 'Коринфский канал',          question_el: 'Διώρυγα Κορίνθου',            correct_answer: 'Коринфский канал',          explanation: 'Канал, соединяющий Саронический и Коринфский заливы', topic: 'vocab' },
  { question: 'Лариса',                    question_el: 'Λάρισα',                       correct_answer: 'Лариса',                    explanation: 'Столица Фессалии, четвёртый город Греции',         topic: 'vocab' },
  { question: 'Лесбос',                    question_el: 'Λέσβος',                       correct_answer: 'Лесбос',                    explanation: 'Остров в Эгейском море, родина Сапфо',             topic: 'vocab' },
  // ── CULTURE ─────────────────────────────────────────────────────────────────
  { question: 'Парфенон',                  question_el: 'Παρθενώνας',                   correct_answer: 'Парфенон',                  explanation: 'Храм богини Афины на Акрополе (V в. до н.э.)',     topic: 'vocab' },
  { question: 'Акрополь',                  question_el: 'Ακρόπολη',                     correct_answer: 'Акрополь',                  explanation: 'Скала с Парфеноном в центре Афин',                 topic: 'vocab' },
  { question: 'Олимпия',                   question_el: 'Ολυμπία',                      correct_answer: 'Олимпия',                   explanation: 'Место проведения первых Олимпийских игр',           topic: 'vocab' },
  { question: 'Олимпийские игры',          question_el: 'Ολυμπιακοί Αγώνες',            correct_answer: 'Олимпийские игры',          explanation: 'Древние игры в Олимпии; возрождены в Афинах 1896 г.', topic: 'vocab' },
  { question: 'Православие',               question_el: 'Ορθοδοξία',                    correct_answer: 'Православие',               explanation: 'Официальная религия Греции',                        topic: 'vocab' },
  { question: 'Пасха',                     question_el: 'Πάσχα',                        correct_answer: 'Пасха',                     explanation: 'Главный религиозный праздник Греции',               topic: 'vocab' },
  { question: 'Карнавал',                  question_el: 'Απόκριες',                     correct_answer: 'Карнавал',                  explanation: 'Три недели праздников перед Великим постом',        topic: 'vocab' },
  { question: 'Рождество',                 question_el: 'Χριστούγεννα',                 correct_answer: 'Рождество',                 explanation: 'Христианский праздник 25 декабря',                  topic: 'vocab' },
  { question: 'философия',                 question_el: 'φιλοσοφία',                    correct_answer: 'философия',                 explanation: 'Греческая философия — основа западной мысли',      topic: 'vocab' },
  { question: 'театр',                     question_el: 'θέατρο',                       correct_answer: 'театр',                     explanation: 'Изобретён в Древней Греции',                        topic: 'vocab' },
  { question: 'трагедия',                  question_el: 'τραγωδία',                     correct_answer: 'трагедия',                  explanation: 'Жанр древнегреческой драмы (Эсхил, Софокл, Еврипид)', topic: 'vocab' },
  { question: 'комедия',                   question_el: 'κωμωδία',                      correct_answer: 'комедия',                   explanation: 'Жанр древнегреческой драмы (Аристофан)',           topic: 'vocab' },
  { question: 'мифология',                 question_el: 'μυθολογία',                    correct_answer: 'мифология',                 explanation: 'Мифы о богах-олимпийцах и героях Древней Греции',  topic: 'vocab' },
  { question: 'поэзия',                    question_el: 'ποίηση',                       correct_answer: 'поэзия',                    explanation: 'Греческие поэты: Кавафис, Элитис, Сеферис',        topic: 'vocab' },
  { question: 'археология',                question_el: 'αρχαιολογία',                  correct_answer: 'археология',                explanation: 'Наука об изучении прошлого по материальным следам', topic: 'vocab' },
  { question: 'музей',                     question_el: 'μουσείο',                      correct_answer: 'музей',                     explanation: 'Εθνικό Αρχαιολογικό Μουσείο — в Афинах',           topic: 'vocab' },
  { question: 'икона',                     question_el: 'εικόνα (αγιογραφία)',          correct_answer: 'икона',                     explanation: 'Священное изображение в православной традиции',    topic: 'vocab' },
  { question: 'церковь',                   question_el: 'Εκκλησία',                     correct_answer: 'церковь',                   explanation: 'Православная церковь Греции',                       topic: 'vocab' },
  { question: 'флаг',                      question_el: 'σημαία',                       correct_answer: 'флаг',                      explanation: 'Синий и белый флаг с крестом',                      topic: 'vocab' },
  { question: 'национальный праздник',     question_el: 'εθνική εορτή',                 correct_answer: 'национальный праздник',     explanation: '25 марта и 28 октября — гос. праздники Греции',    topic: 'vocab' },
  { question: 'язык',                      question_el: 'γλώσσα',                       correct_answer: 'язык',                      explanation: 'Новогреческий — официальный язык Греции',           topic: 'vocab' },
  { question: 'искусство',                 question_el: 'τέχνη',                        correct_answer: 'искусство',                 explanation: 'Греческое искусство от античности до наших дней',  topic: 'vocab' },
  { question: 'архитектура',               question_el: 'αρχιτεκτονική',                correct_answer: 'архитектура',               explanation: 'Древнегреческая архитектура — основа западной',    topic: 'vocab' },
  { question: 'скульптура',                question_el: 'γλυπτική',                     correct_answer: 'скульптура',                explanation: 'Мрамор — главный материал греческой скульптуры',   topic: 'vocab' },
  { question: 'традиция',                  question_el: 'παράδοση',                     correct_answer: 'традиция',                  explanation: 'Обычаи, передаваемые из поколения в поколение',    topic: 'vocab' },
  { question: 'культура, цивилизация',     question_el: 'πολιτισμός',                   correct_answer: 'культура, цивилизация',     explanation: 'Греческая цивилизация — основа западного мира',    topic: 'vocab' },
  { question: '25 марта',                  question_el: '25η Μαρτίου',                  correct_answer: '25 марта',                  explanation: 'День независимости Греции (1821)',                  topic: 'vocab' },
  { question: '28 октября',                question_el: '28η Οκτωβρίου',                correct_answer: '28 октября',                explanation: 'День Охи — отказ Метаксаса Муссолини (1940)',       topic: 'vocab' },
  { question: 'Новый год',                 question_el: 'Πρωτοχρονιά',                  correct_answer: 'Новый год',                 explanation: 'День Святого Василия — 1 января',                  topic: 'vocab' },
  { question: 'Древняя Греция',            question_el: 'Αρχαία Ελλάδα',               correct_answer: 'Древняя Греция',            explanation: 'Колыбель европейской цивилизации',                 topic: 'vocab' },
  { question: 'демократия',                question_el: 'δημοκρατία',                   correct_answer: 'демократия',                explanation: 'Изобретена в Афинах V в. до н.э.',                 topic: 'vocab' },
].map(item => ({
  ...item,
  correct_answer_el: null,
  wrong_answers: [] as string[],
  wrong_answers_el: [] as string[],
  explanation_el: null,
}));

async function main() {
  console.log(`Inserting ${VOCAB_ITEMS.length} vocabulary items...`);

  // Insert in batches of 50 to avoid request size limits
  const BATCH = 50;
  let total = 0;
  for (let i = 0; i < VOCAB_ITEMS.length; i += BATCH) {
    const batch = VOCAB_ITEMS.slice(i, i + BATCH);
    const { error } = await supabase.from('questions').insert(batch);
    if (error) {
      console.error(`Batch ${i / BATCH + 1} error:`, error.message);
      process.exit(1);
    }
    total += batch.length;
    console.log(`  ✓ ${total}/${VOCAB_ITEMS.length}`);
  }

  console.log('Done!');
}

main().catch(console.error);
